// Pure formatters for the PR verdict comment. Each formatter takes a
// CLI report (JSON) and returns a section of the final Markdown
// comment. Splitting these out lets us unit-test the comment shape
// without spinning up an actual GitHub workflow.

const STICKY_MARKER = "<!-- repograph-intelligence-verdict -->";
const MAX_ROWS = 25;

/** Joined Markdown comment to post on the PR. */
export function renderComment(sections) {
  const overall = sections.overall;
  const verdict = overall.passed ? "✅ **All RepoGraph gates passed**" : "❌ **RepoGraph found regressions**";
  const summary = describeOverall(overall);
  const blocks = [STICKY_MARKER, `## ${verdict}`, "", summary, ""];

  for (const section of sections.gates) {
    blocks.push(`### ${section.title}`);
    blocks.push("");
    blocks.push(section.body);
    blocks.push("");
  }

  blocks.push("");
  blocks.push(`<sub>Generated by [RepoGraph Intelligence](https://github.com/Rajveerx11/repograph-intelligence) at ${overall.generatedAt}.</sub>`);
  return blocks.join("\n");
}

export function isRepoGraphComment(body) {
  return typeof body === "string" && body.includes(STICKY_MARKER);
}

export function policySection(report) {
  if (!report) {
    return null;
  }
  const counts = report.counts ?? {};
  const total = (counts.error ?? 0) + (counts.warning ?? 0) + (counts.info ?? 0);
  const status = report.passed ? "✅" : "❌";
  const lines = [
    `${status} Rules evaluated: **${report.rulesEvaluated ?? 0}**`,
    `Violations — errors: ${counts.error ?? 0}, warnings: ${counts.warning ?? 0}, info: ${counts.info ?? 0}`
  ];
  if (total > 0) {
    lines.push("");
    lines.push("| Severity | Rule | Path / Target | Message |");
    lines.push("| --- | --- | --- | --- |");
    for (const violation of (report.violations ?? []).slice(0, MAX_ROWS)) {
      const target = violation.target ?? violation.from ?? "—";
      lines.push(`| ${escapeMd(violation.severity)} | \`${escapeInline(violation.ruleId)}\` | \`${escapeInline(target)}\` | ${escapeMd(violation.message)} |`);
    }
    if ((report.violations ?? []).length > MAX_ROWS) {
      lines.push(`| … | … | … | ${(report.violations ?? []).length - MAX_ROWS} more rows truncated |`);
    }
  }
  return { title: "Architecture Policy", body: lines.join("\n"), passed: report.passed === true };
}

export function apiDiffSection(report) {
  if (!report) {
    return null;
  }
  const summary = report.summary ?? {};
  const breaking = summary.breaking ?? 0;
  const status = breaking === 0 ? "✅" : "❌";
  const lines = [
    `${status} Base exports: **${summary.baseExports ?? 0}** · Head exports: **${summary.headExports ?? 0}**`,
    `Added: ${summary.added ?? 0}, Removed: ${summary.removed ?? 0}, Changed: ${summary.changed ?? 0}`,
    `Breaking changes (removed + changed): **${breaking}**`
  ];
  const rows = [
    ...(report.removed ?? []).slice(0, MAX_ROWS).map((entry) => ({
      verb: "-",
      label: `\`${escapeInline(entry.path)}\` — \`${escapeInline(entry.name)}\` (${escapeInline(entry.type ?? "?")}) — _removed_`
    })),
    ...(report.changed ?? []).slice(0, MAX_ROWS).map((entry) => ({
      verb: "~",
      label: `\`${escapeInline(entry.path)}\` — \`${escapeInline(entry.name)}\` — kind \`${escapeInline(entry.baseType ?? "?")}\` → \`${escapeInline(entry.headType ?? "?")}\``
    }))
  ];
  if (rows.length > 0) {
    lines.push("");
    lines.push("**Breaking detail:**");
    for (const row of rows.slice(0, MAX_ROWS)) {
      lines.push(`- ${row.verb} ${row.label}`);
    }
    if (rows.length > MAX_ROWS) {
      lines.push(`- … ${rows.length - MAX_ROWS} more truncated`);
    }
  }
  return { title: "API Surface Diff", body: lines.join("\n"), passed: breaking === 0 };
}

export function driftSection(report) {
  if (!report) {
    return null;
  }
  const status = report.passed ? "✅" : "❌";
  const lines = [
    `${status} Fingerprint changed: **${report.summary?.fingerprintChanged ?? false}**, severity: **${report.summary?.severity ?? "unknown"}**`,
    "",
    "| Check | Baseline | Current | Delta | Threshold | Status |",
    "| --- | --- | --- | --- | --- | --- |"
  ];
  for (const check of report.checks ?? []) {
    const threshold = check.threshold === null || check.threshold === undefined || !Number.isFinite(check.threshold) ? "∞" : check.threshold;
    lines.push(`| ${escapeMd(check.name)} | ${check.baseline} | ${check.current} | ${check.delta} | ${threshold} | ${check.passed ? "PASS" : "FAIL"} |`);
  }
  if (!report.passed && report.summary?.failedChecks?.length) {
    lines.push("");
    lines.push(`**Failed checks**: ${report.summary.failedChecks.map(escapeMd).join(", ")}`);
  }
  return { title: "Drift Gate", body: lines.join("\n"), passed: report.passed === true };
}

export function testSelectionSection(report) {
  if (!report) {
    return null;
  }
  const summary = report.summary ?? {};
  const lines = [
    `Changed files: **${summary.changed ?? 0}**`,
    `Affected files: **${summary.affected ?? 0}** (blast radius ${summary.blastRadius ?? 0}, risk **${summary.risk?.level ?? "n/a"}**)`,
    `Tests to run: **${summary.tests ?? 0}** of ${summary.totalTestFiles ?? 0}` + (summary.coverageRatio !== null && summary.coverageRatio !== undefined ? ` (${summary.coverageRatio}% of suite)` : "")
  ];
  if ((report.tests ?? []).length > 0) {
    lines.push("");
    lines.push("<details><summary>Selected tests</summary>\n");
    for (const test of (report.tests ?? []).slice(0, MAX_ROWS)) {
      lines.push(`- \`${escapeInline(test)}\``);
    }
    if ((report.tests ?? []).length > MAX_ROWS) {
      lines.push(`- … ${(report.tests ?? []).length - MAX_ROWS} more truncated`);
    }
    lines.push("\n</details>");
  } else {
    lines.push("");
    lines.push("_No tests selected. Either the diff has no test coverage or the test patterns missed every dependent test file._");
  }
  // Test selection is informational — never fails the gate.
  return { title: "Test Selection (informational)", body: lines.join("\n"), passed: true };
}

export function escapeMd(value) {
  if (value === null || value === undefined) {
    return "";
  }
  return String(value).replace(/\|/g, "\\|").replace(/`/g, "\\`").replace(/\r?\n/g, " ");
}

/**
 * Escape a value for use inside an inline code span (\`${value}\`).
 * Backticks would prematurely close the span; pipes would still break
 * a surrounding Markdown table even though they're inside the span.
 * Strip both, plus angle brackets so a hostile file name cannot inject
 * raw HTML through GitHub's renderer.
 */
export function escapeInline(value) {
  if (value === null || value === undefined) {
    return "";
  }
  return String(value)
    .replace(/`/g, "'")
    .replace(/\|/g, "\\|")
    .replace(/[<>]/g, "")
    .replace(/\r?\n/g, " ");
}

function describeOverall(overall) {
  const failed = overall.failedGates;
  if (failed.length === 0) {
    return "No gates fired. The change is structurally clean.";
  }
  return `Failed gates: ${failed.map((name) => `\`${escapeInline(name)}\``).join(", ")}.`;
}

export { STICKY_MARKER, MAX_ROWS };
