const VALID_RANKDIRS = new Set(["LR", "TB", "TD", "RL", "BT"]);
const DEFAULT_MAX_NODES = 200;
const DEFAULT_MAX_EDGES = 400;
const MAX_LABEL_LENGTH = 60;

/**
 * Convert a RepoGraph into GraphViz DOT source. The output renders in
 * Graphviz proper, dot/neato/twopi, Gephi, yEd, and any tool that can
 * `dot -Tpng`/`dot -Tsvg` a tracefile. Sister export to `toMermaid` —
 * options mirror that function so a single set of UI controls can drive
 * both renderers.
 *
 * @param {object} graph
 * @param {object} [options]
 * @param {"LR"|"TB"|"TD"|"RL"|"BT"} [options.rankdir="LR"] - `TD` is
 *        accepted as a Mermaid-style alias for GraphViz `TB`.
 * @param {boolean} [options.includeSymbols=false]
 * @param {boolean} [options.includePackages=true]
 * @param {boolean} [options.includeContains=false]
 * @param {number}  [options.maxNodes=200]
 * @param {number}  [options.maxEdges=400]
 * @returns {string} DOT source, terminated with a newline.
 */
export function toDot(graph, options = {}) {
  if (!graph || !Array.isArray(graph.nodes) || !Array.isArray(graph.edges)) {
    throw new Error("toDot requires a graph with nodes and edges arrays.");
  }

  const rankdir = normalizeRankdir(options.rankdir);
  const includeSymbols = options.includeSymbols === true;
  const includePackages = options.includePackages !== false;
  const includeContains = options.includeContains === true;
  const maxNodes = boundedInt(options.maxNodes, DEFAULT_MAX_NODES, 1, 5000);
  const maxEdges = boundedInt(options.maxEdges, DEFAULT_MAX_EDGES, 1, 20000);

  const allowedTypes = new Set(["file"]);
  if (includeSymbols) {
    allowedTypes.add("function");
    allowedTypes.add("class");
    allowedTypes.add("method");
    allowedTypes.add("interface");
    allowedTypes.add("module");
  }
  if (includePackages) {
    allowedTypes.add("package");
  }

  const eligibleNodes = graph.nodes.filter((node) => allowedTypes.has(node.type));
  const truncated = eligibleNodes.length > maxNodes;
  const renderedNodes = eligibleNodes.slice(0, maxNodes);
  const renderedIds = new Set(renderedNodes.map((node) => node.id));
  const aliasById = buildAliasMap(renderedNodes);

  const edgeLines = [];
  let edgesTruncated = false;
  for (const edge of graph.edges) {
    if (edgeLines.length >= maxEdges) {
      edgesTruncated = true;
      break;
    }
    if (!renderedIds.has(edge.from) || !renderedIds.has(edge.to)) {
      continue;
    }
    if (edge.type === "contains" && !includeContains) {
      continue;
    }
    edgeLines.push(formatEdge(edge, aliasById));
  }

  const lines = ["digraph RepoGraph {"];
  lines.push("  // Generated by RepoGraph Intelligence — do not edit by hand.");
  lines.push(`  rankdir=${rankdir};`);
  lines.push("  bgcolor=\"#ffffff\";");
  lines.push("  node [fontname=\"Helvetica\", fontsize=10, style=\"filled,rounded\", shape=box, color=\"#1d4ed8\", fillcolor=\"#dbeafe\", fontcolor=\"#0f172a\"];");
  lines.push("  edge [fontname=\"Helvetica\", fontsize=9, color=\"#475569\"];");

  for (const node of renderedNodes) {
    lines.push(`  ${formatNode(node, aliasById)}`);
  }

  if (edgeLines.length) {
    lines.push("");
    lines.push(...edgeLines.map((edge) => `  ${edge}`));
  }

  if (truncated || edgesTruncated) {
    const parts = [];
    if (truncated) {
      parts.push(`nodes ${renderedNodes.length}/${eligibleNodes.length}`);
    }
    if (edgesTruncated) {
      parts.push(`edges capped at ${maxEdges}`);
    }
    lines.push("");
    lines.push(`  // Truncated: ${parts.join(", ")}.`);
  }

  lines.push("}");
  return `${lines.join("\n")}\n`;
}

function normalizeRankdir(value) {
  if (value == null) {
    return "LR";
  }
  if (typeof value !== "string") {
    throw new Error("toDot rankdir must be a string.");
  }
  const upper = value.toUpperCase();
  if (!VALID_RANKDIRS.has(upper)) {
    throw new Error(`toDot rankdir must be one of LR, TB, TD, RL, BT. Got: ${value}`);
  }
  return upper === "TD" ? "TB" : upper;
}

function buildAliasMap(nodes) {
  const map = new Map();
  let counter = 0;
  for (const node of nodes) {
    counter += 1;
    map.set(node.id, `n${counter}`);
  }
  return map;
}

function formatNode(node, aliasById) {
  const alias = aliasById.get(node.id);
  const label = escapeLabel(node.label ?? node.path ?? node.id);
  const attrs = nodeAttrs(node, label);
  return `${alias} [${attrs}];`;
}

function nodeAttrs(node, escapedLabel) {
  const labelAttr = `label="${escapedLabel}"`;
  switch (node.type) {
    case "package":
      return `${labelAttr}, shape=ellipse, fillcolor="#e2e8f0", color="#475569"`;
    case "function":
    case "method":
    case "class":
    case "interface":
      return `${labelAttr}, shape=ellipse, fillcolor="#dcfce7", color="#16a34a"`;
    case "module":
      return `${labelAttr}, shape=box3d, fillcolor="#fef3c7", color="#b45309"`;
    case "file":
    default:
      return `${labelAttr}, shape=box, fillcolor="#dbeafe", color="#1d4ed8"`;
  }
}

function formatEdge(edge, aliasById) {
  const from = aliasById.get(edge.from);
  const to = aliasById.get(edge.to);
  switch (edge.type) {
    case "dependency":
      return `${from} -> ${to} [style=dashed, color="#9333ea"];`;
    case "exports":
      return `${from} -> ${to} [penwidth=2, color="#16a34a"];`;
    case "references":
      return `${from} -> ${to} [style=dotted, label="ref"];`;
    case "contains":
      return `${from} -> ${to} [arrowhead=none, color="#94a3b8"];`;
    case "imports":
    default:
      return `${from} -> ${to};`;
  }
}

function escapeLabel(value) {
  const str = String(value ?? "");
  const truncated = str.length > MAX_LABEL_LENGTH ? `${str.slice(0, MAX_LABEL_LENGTH - 1)}…` : str;
  return truncated
    .replace(/\\/g, "\\\\")
    .replace(/"/g, "\\\"")
    .replace(/\r?\n/g, " ")
    // Drop control characters that can crash dot's lexer.
    .replace(/[\x00-\x1f\x7f]/g, " ");
}

function boundedInt(value, fallback, min, max) {
  const number = Number(value ?? fallback);
  if (!Number.isInteger(number)) {
    return fallback;
  }
  return Math.min(max, Math.max(min, number));
}
