const VALID_DIRECTIONS = new Set(["LR", "TD", "TB", "RL", "BT"]);
const DEFAULT_MAX_NODES = 200;
const DEFAULT_MAX_EDGES = 400;
const MAX_LABEL_LENGTH = 60;

/**
 * Convert a RepoGraph into Mermaid flowchart syntax that renders natively in
 * GitHub, GitLab, Notion, and most modern Markdown viewers.
 *
 * The output is deterministic for a given graph + options pair so it can be
 * diffed in CI to detect structural drift.
 *
 * @param {object} graph - Normalized RepoGraph (must contain `nodes` and `edges`).
 * @param {object} [options]
 * @param {"LR"|"TD"|"TB"|"RL"|"BT"} [options.direction="LR"] - Mermaid layout direction.
 * @param {boolean} [options.includeSymbols=false] - Include function/class/method nodes.
 * @param {boolean} [options.includePackages=true] - Include external package nodes.
 * @param {boolean} [options.includeContains=false] - Render `contains` edges (file → symbol).
 * @param {number}  [options.maxNodes=200] - Truncate nodes beyond this count (Mermaid renderers degrade past ~500).
 * @param {number}  [options.maxEdges=400] - Truncate edges beyond this count.
 * @returns {string} Mermaid flowchart source, terminated with a newline.
 */
export function toMermaid(graph, options = {}) {
  if (!graph || !Array.isArray(graph.nodes) || !Array.isArray(graph.edges)) {
    throw new Error("toMermaid requires a graph with nodes and edges arrays.");
  }

  const direction = VALID_DIRECTIONS.has(options.direction) ? options.direction : "LR";
  const includeSymbols = options.includeSymbols === true;
  const includePackages = options.includePackages !== false;
  const includeContains = options.includeContains === true;
  const maxNodes = boundedInt(options.maxNodes, DEFAULT_MAX_NODES, 1, 5000);
  const maxEdges = boundedInt(options.maxEdges, DEFAULT_MAX_EDGES, 1, 20000);

  const allowedTypes = new Set(["file"]);
  if (includeSymbols) {
    allowedTypes.add("function");
    allowedTypes.add("class");
    allowedTypes.add("method");
    allowedTypes.add("interface");
    allowedTypes.add("module");
  }
  if (includePackages) {
    allowedTypes.add("package");
  }

  const eligibleNodes = graph.nodes.filter((node) => allowedTypes.has(node.type));
  const truncated = eligibleNodes.length > maxNodes;
  const renderedNodes = eligibleNodes.slice(0, maxNodes);
  const renderedIds = new Set(renderedNodes.map((node) => node.id));
  const aliasById = buildAliasMap(renderedNodes);

  const edgeLines = [];
  let edgesTruncated = false;
  for (const edge of graph.edges) {
    if (edgeLines.length >= maxEdges) {
      edgesTruncated = true;
      break;
    }
    if (!renderedIds.has(edge.from) || !renderedIds.has(edge.to)) {
      continue;
    }
    if (edge.type === "contains" && !includeContains) {
      continue;
    }
    edgeLines.push(formatEdge(edge, aliasById));
  }

  const lines = [`flowchart ${direction}`];
  lines.push("  %% Generated by RepoGraph Intelligence — do not edit by hand.");
  lines.push("  classDef file fill:#dbeafe,stroke:#1d4ed8,color:#0f172a;");
  lines.push("  classDef package fill:#e2e8f0,stroke:#475569,color:#0f172a;");
  lines.push("  classDef symbol fill:#dcfce7,stroke:#16a34a,color:#0f172a;");
  lines.push("  classDef module fill:#fef3c7,stroke:#b45309,color:#0f172a;");

  for (const node of renderedNodes) {
    lines.push(`  ${formatNode(node, aliasById)}`);
  }

  if (edgeLines.length) {
    lines.push("");
    lines.push(...edgeLines.map((edge) => `  ${edge}`));
  }

  if (truncated || edgesTruncated) {
    const parts = [];
    if (truncated) {
      parts.push(`nodes ${renderedNodes.length}/${eligibleNodes.length}`);
    }
    if (edgesTruncated) {
      parts.push(`edges capped at ${maxEdges}`);
    }
    lines.push("");
    lines.push(`  %% Truncated: ${parts.join(", ")}.`);
  }

  return `${lines.join("\n")}\n`;
}

function buildAliasMap(nodes) {
  const map = new Map();
  let counter = 0;
  for (const node of nodes) {
    counter += 1;
    map.set(node.id, `n${counter}`);
  }
  return map;
}

function formatNode(node, aliasById) {
  const alias = aliasById.get(node.id);
  const label = escapeLabel(node.label ?? node.path ?? node.id);
  const klass = mermaidClassFor(node.type);
  switch (node.type) {
    case "package":
      return `${alias}(["${label}"]):::${klass}`;
    case "function":
    case "method":
    case "class":
    case "interface":
      return `${alias}(["${label}"]):::${klass}`;
    case "module":
      return `${alias}[["${label}"]]:::${klass}`;
    case "file":
    default:
      return `${alias}["${label}"]:::${klass}`;
  }
}

function formatEdge(edge, aliasById) {
  const from = aliasById.get(edge.from);
  const to = aliasById.get(edge.to);
  switch (edge.type) {
    case "dependency":
      return `${from} -.-> ${to}`;
    case "exports":
      return `${from} ==> ${to}`;
    case "references":
      return `${from} -. ref .-> ${to}`;
    case "contains":
      return `${from} --- ${to}`;
    case "imports":
    default:
      return `${from} --> ${to}`;
  }
}

function mermaidClassFor(type) {
  if (type === "package") return "package";
  if (type === "module") return "module";
  if (type === "file") return "file";
  return "symbol";
}

function escapeLabel(value) {
  const str = String(value ?? "");
  const truncated = str.length > MAX_LABEL_LENGTH ? `${str.slice(0, MAX_LABEL_LENGTH - 1)}…` : str;
  return truncated
    .replace(/\\/g, "\\\\")
    .replace(/"/g, "\\\"")
    .replace(/\r?\n/g, " ")
    .replace(/[<>]/g, " ");
}

function boundedInt(value, fallback, min, max) {
  const number = Number(value ?? fallback);
  if (!Number.isInteger(number)) {
    return fallback;
  }
  return Math.min(max, Math.max(min, number));
}
