import assert from "node:assert/strict";
import test from "node:test";
import {
  STICKY_MARKER,
  apiDiffSection,
  driftSection,
  escapeMd,
  isRepoGraphComment,
  policySection,
  renderComment,
  testSelectionSection
} from "../src/formatters.js";

test("renderComment wraps sections with sticky marker, pass headline, and footer", () => {
  const comment = renderComment({
    overall: { passed: true, failedGates: [], generatedAt: "2026-05-18T00:00:00Z" },
    gates: [{ title: "Policy", body: "ok", passed: true }]
  });
  assert.ok(comment.startsWith(STICKY_MARKER));
  assert.match(comment, /All RepoGraph gates passed/);
  assert.match(comment, /No gates fired/);
  assert.match(comment, /### Policy/);
  assert.match(comment, /Generated by \[RepoGraph Intelligence\]/);
});

test("renderComment names failed gates in the headline summary", () => {
  const comment = renderComment({
    overall: { passed: false, failedGates: ["policy", "drift"], generatedAt: "2026-05-18T00:00:00Z" },
    gates: []
  });
  assert.match(comment, /RepoGraph found regressions/);
  assert.match(comment, /`policy`, `drift`/);
});

test("isRepoGraphComment recognises only its own sticky marker", () => {
  assert.equal(isRepoGraphComment(`${STICKY_MARKER}\nsomething`), true);
  assert.equal(isRepoGraphComment("a totally unrelated comment"), false);
  assert.equal(isRepoGraphComment(null), false);
  assert.equal(isRepoGraphComment(undefined), false);
});

test("policySection emits passing summary when no violations and a violation table when there are", () => {
  const passing = policySection({ rulesEvaluated: 5, counts: { error: 0, warning: 0, info: 0 }, violations: [], passed: true });
  assert.equal(passing.passed, true);
  assert.match(passing.body, /Rules evaluated/);
  assert.doesNotMatch(passing.body, /\| --- \|/);

  const failing = policySection({
    rulesEvaluated: 5,
    counts: { error: 2, warning: 1, info: 0 },
    passed: false,
    violations: [
      { severity: "error", ruleId: "no-domain-into-infra", ruleType: "forbid-import", message: "src/domain/user.ts imports src/infra/db.ts", target: "src/domain/user.ts" },
      { severity: "warning", ruleId: "small-files", ruleType: "max-lines", message: "src/util.ts has 600 lines", target: "src/util.ts" }
    ]
  });
  assert.equal(failing.passed, false);
  assert.match(failing.body, /\| Severity \| Rule/);
  assert.match(failing.body, /no-domain-into-infra/);
  assert.match(failing.body, /small-files/);
});

test("policySection truncates long violation lists with a trailing summary row", () => {
  const violations = Array.from({ length: 40 }, (_, index) => ({
    severity: "error",
    ruleId: `rule-${index}`,
    ruleType: "forbid-import",
    target: `src/file${index}.ts`,
    message: `violation ${index}`
  }));
  const section = policySection({
    rulesEvaluated: 1,
    counts: { error: 40, warning: 0, info: 0 },
    passed: false,
    violations
  });
  const lines = section.body.split("\n").filter((line) => line.startsWith("| "));
  // Header row + 25 violations + truncation summary row + separator
  assert.ok(lines.length <= 28, "violation table should be capped at MAX_ROWS rows plus headers");
  assert.match(section.body, /15 more rows truncated/);
});

test("apiDiffSection reports pass with zero breaking and lists removed/changed entries on fail", () => {
  const passing = apiDiffSection({
    summary: { baseExports: 10, headExports: 12, added: 2, removed: 0, changed: 0, breaking: 0 }
  });
  assert.equal(passing.passed, true);

  const failing = apiDiffSection({
    summary: { baseExports: 10, headExports: 9, added: 0, removed: 2, changed: 1, breaking: 3 },
    removed: [
      { path: "src/api.ts", name: "fetchUser", type: "function" }
    ],
    changed: [
      { path: "src/api.ts", name: "User", baseType: "interface", headType: "class" }
    ]
  });
  assert.equal(failing.passed, false);
  assert.match(failing.body, /Breaking changes/);
  assert.match(failing.body, /fetchUser/);
  assert.match(failing.body, /interface.*class/);
});

test("driftSection renders the per-check table and surfaces failed-check names", () => {
  const report = {
    passed: false,
    summary: { fingerprintChanged: true, severity: "medium", failedChecks: ["newCycles"] },
    checks: [
      { name: "newCycles", baseline: 0, current: 2, delta: 2, threshold: 0, passed: false },
      { name: "addedFiles", baseline: 10, current: 12, delta: 2, threshold: Infinity, passed: true }
    ]
  };
  const section = driftSection(report);
  assert.equal(section.passed, false);
  assert.match(section.body, /\| newCycles \| 0 \| 2 \| 2 \| 0 \| FAIL \|/);
  assert.match(section.body, /\| addedFiles \|.*\| ∞ \| PASS \|/);
  assert.match(section.body, /Failed checks.*newCycles/);
});

test("testSelectionSection is always informational (passed=true) and reports the selected tests", () => {
  const section = testSelectionSection({
    summary: { changed: 1, affected: 5, blastRadius: 4, risk: { level: "medium" }, tests: 2, totalTestFiles: 8, coverageRatio: 25 },
    tests: ["test/auth.test.ts", "test/db.test.ts"]
  });
  assert.equal(section.passed, true);
  assert.match(section.body, /Tests to run: \*\*2\*\* of 8/);
  assert.match(section.body, /test\/auth\.test\.ts/);
});

test("escapeMd escapes pipes, backticks, and newlines so they survive a Markdown table", () => {
  assert.equal(escapeMd("a|b"), "a\\|b");
  assert.equal(escapeMd("a`b"), "a\\`b");
  assert.equal(escapeMd("a\nb"), "a b");
  assert.equal(escapeMd(null), "");
});
